apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: ingress
data:
  access-token: "your access token..."
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@example.com
    privateKeySecretRef:
      name: letsencrypt
    # you may need a different DNS provider or something.
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
